'<text a1>'
'/ items = word_absent_1'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a2>'
'/ items = word_absent_2'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a3>'
'/ items = word_absent_3'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a4>'
'/ items = word_absent_4'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a5>'
'/ items = word_absent_5'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a6>'
'/ items = word_absent_6'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a7>'
'/ items = word_absent_7'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a8>'
'/ items = word_absent_8'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a9>'
'/ items = word_absent_9'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a10>'
'/ items = word_absent_10'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a11>'
'/ items = word_absent_11'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a12>'
'/ items = word_absent_12'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a13>'
'/ items = word_absent_13'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a14>'
'/ items = word_absent_14'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a15>'
'/ items = word_absent_15'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a16>'
'/ items = word_absent_16'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a17>'
'/ items = word_absent_17'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a18>'
'/ items = word_absent_18'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a19>'
'/ items = word_absent_19'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a20>'
'/ items = word_absent_20'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a21>'
'/ items = word_absent_21'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a22>'
'/ items = word_absent_22'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a23>'
'/ items = word_absent_23'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a24>'
'/ items = word_absent_24'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a25>'
'/ items = word_absent_25'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a26>'
'/ items = word_absent_26'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a27>'
'/ items = word_absent_27'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a28>'
'/ items = word_absent_28'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a29>'
'/ items = word_absent_29'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a30>'
'/ items = word_absent_30'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a31>'
'/ items = word_absent_31'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a32>'
'/ items = word_absent_32'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a33>'
'/ items = word_absent_33'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a34>'
'/ items = word_absent_34'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a35>'
'/ items = word_absent_35'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a36>'
'/ items = word_absent_36'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a37>'
'/ items = word_absent_37'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a38>'
'/ items = word_absent_38'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a39>'
'/ items = word_absent_39'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'
'<text a40>'
'/ items = word_absent_40'
'/ select = noreplace'
'/ vposition = values.textPosition'
'/ fontstyle = ("Avenir next", values.MYfontsize, true, false, false, false, 5, 0)'
'</text>'